// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3lx_wGip2jA4lAwBwQU-u8hY5LGoxy-Q',
    appId: '1:1037814604190:web:d7ab8582385a440e42f68f',
    messagingSenderId: '1037814604190',
    projectId: 'investserv',
    authDomain: 'investserv.firebaseapp.com',
    storageBucket: 'investserv.firebasestorage.app',
    measurementId: 'G-4W02EG6W1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVKSKTLJZ91-erg59C26_uH9hZPwWjexc',
    appId: '1:1037814604190:android:ba321b0d8aa0446042f68f',
    messagingSenderId: '1037814604190',
    projectId: 'investserv',
    storageBucket: 'investserv.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB43ggi4bf99ngkKDWG-HbSHiDv-cbZe-c',
    appId: '1:1037814604190:ios:796622020095a72242f68f',
    messagingSenderId: '1037814604190',
    projectId: 'investserv',
    storageBucket: 'investserv.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB43ggi4bf99ngkKDWG-HbSHiDv-cbZe-c',
    appId: '1:1037814604190:ios:796622020095a72242f68f',
    messagingSenderId: '1037814604190',
    projectId: 'investserv',
    storageBucket: 'investserv.firebasestorage.app',
    iosBundleId: 'com.example.meuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3lx_wGip2jA4lAwBwQU-u8hY5LGoxy-Q',
    appId: '1:1037814604190:web:1f5d797fae55899142f68f',
    messagingSenderId: '1037814604190',
    projectId: 'investserv',
    authDomain: 'investserv.firebaseapp.com',
    storageBucket: 'investserv.firebasestorage.app',
    measurementId: 'G-S5D8PYZXGQ',
  );
}
